### ISSUE TITLE
Корректировка выравнивания

### ISSUE THREAD

**Issue by dikarimova73** [i-karimov/sky-front#3]
1) цифру 6 отцентрировать по вертикали относительно всего текстового блока.
2) Выделенный участок разместить по центру под верхним текстовым блоком. Уместить в воображаемые равные отступы справа и слева экрана
![image](https://user-images.githubusercontent.com/57755998/68922537-51ac7680-0795-11ea-91a6-46c31c6e52e4.png)

**Comment by i-karimov** [comment]
![image](https://user-images.githubusercontent.com/42221459/69239387-84020d80-0bb3-11ea-8a98-069696d71bb7.png)
