### ISSUE TITLE
Слишком большие отступы

### ISSUE THREAD

**Issue by dikarimova73** [i-karimov/sky-front#7]
![image](https://user-images.githubusercontent.com/57755998/68932623-7102ce00-07ac-11ea-8302-cebdbe0c78f3.png)

Сделай, пожалуйста, компактнее этот участок.

**Comment by i-karimov** [comment]
![image](https://user-images.githubusercontent.com/42221459/69240628-55396680-0bb6-11ea-939f-9ce760875eb6.png)
